export const ServiceOrderChannel = {
  OWN_APP_SIMULATED_ORDER: "OWN_APP_SIMULATED_ORDER",
  PARTNER_APP_SIMULATED_ORDER: "PARTNER_APP_SIMULATED_ORDER",
};

export const ServiceOrderStatus = {
  WAITING_PRICE_ESTIMATE: "WAITING_PRICE_ESTIMATE",
  WAITING_ROBOTAXI_CALL: "WAITING_ROBOTAXI_CALL",
  WAITING_ROBOTAXI_ASSIGNMENT: "WAITING_ROBOTAXI_ASSIGNMENT",
  ROBOTAXI_ASSIGNMENT_FAILED: "ROBOTAXI_ASSIGNMENT_FAILED",
  ON_THE_WAY_PICKUP: "ON_THE_WAY_PICKUP",
  WAITING_CUSTOMER_BOARDING: "WAITING_CUSTOMER_BOARDING",
  CUSTOMER_ONBOARD: "CUSTOMER_ONBOARD",
  ON_THE_WAY_DESTINATION: "ON_THE_WAY_DESTINATION",
  SETTLING: "SETTLING",
  CREATED: "CREATED",
  CALCULATING_PRICE: "CALCULATING_PRICE",
  WAITING_CUSTOMER_CONFIRM: "WAITING_CUSTOMER_CONFIRM",
  WAITING_FOR_VEHICLE: "WAITING_FOR_VEHICLE",
  VEHICLE_ASSIGNED: "VEHICLE_ASSIGNED",
  VEHICLE_ON_THE_WAY_TO_PICKUP: "VEHICLE_ON_THE_WAY_TO_PICKUP",
  WAITING_PASSENGER_BOARDING: "WAITING_PASSENGER_BOARDING",
  PASSENGER_ONBOARD: "PASSENGER_ONBOARD",
  ON_THE_WAY_TO_DESTINATION: "ON_THE_WAY_TO_DESTINATION",
  ARRIVED_DESTINATION: "ARRIVED_DESTINATION",
  WAITING_OPERATION_DECISION: "WAITING_OPERATION_DECISION",
  MATCH_FAILED: "MATCH_FAILED",
  MATCHING_FAILED: "MATCHING_FAILED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const PaymentStatus = {
  NOT_REQUIRED: "NOT_REQUIRED",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  PAID: "PAID",
  PAYMENT_FAILED: "PAYMENT_FAILED",
};

export function createServiceOrder(order) {
  return order;
}
