export const ServiceOrderChannel = {
  OWN_APP_SIMULATED_ORDER: "OWN_APP_SIMULATED_ORDER",
  PARTNER_APP_SIMULATED_ORDER: "PARTNER_APP_SIMULATED_ORDER",
};

export const ServiceOrderStatus = {
  CREATED: "CREATED",
  CALCULATING_PRICE: "CALCULATING_PRICE",
  WAITING_CUSTOMER_CONFIRM: "WAITING_CUSTOMER_CONFIRM",
  WAITING_FOR_VEHICLE: "WAITING_FOR_VEHICLE",
  VEHICLE_ASSIGNED: "VEHICLE_ASSIGNED",
  MATCH_FAILED: "MATCH_FAILED",
  MATCHING_FAILED: "MATCHING_FAILED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const PaymentStatus = {
  NOT_REQUIRED: "NOT_REQUIRED",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  PAID: "PAID",
  PAYMENT_FAILED: "PAYMENT_FAILED",
};

export function createServiceOrder(order) {
  return order;
}
