export const TaskType = {
  READINESS_CHECK: "READINESS_CHECK",
  DEPLOYMENT: "DEPLOYMENT",
};

export const ReadinessTaskStatus = {
  WAITING_ASSIGNMENT: "WAITING_ASSIGNMENT",
  WAITING_CHECK: "WAITING_CHECK",
  CHECKING: "CHECKING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
};

export const TaskPriority = {
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  URGENT: "URGENT",
};

export const DeploymentTaskStatus = {
  WAITING_ROUTE: "WAITING_ROUTE",
  WAITING_START: "WAITING_START",
  MOVING: "MOVING",
  ARRIVED: "ARRIVED",
  ARRIVAL_ABNORMAL: "ARRIVAL_ABNORMAL",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
};

export const RouteExecutionStatus = {
  WAITING_START: "WAITING_START",
  MOVING: "MOVING",
  ARRIVED: "ARRIVED",
  ARRIVAL_ABNORMAL: "ARRIVAL_ABNORMAL",
  PAUSED: "PAUSED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
};

export const TriggerType = {
  AUTO: "AUTO",
  MANUAL: "MANUAL",
};

export const TaskSourceType = {
  OPS_CENTER: "OPS_CENTER",
  MANUAL_OPERATION: "MANUAL_OPERATION",
  SUPPLY_ADJUSTMENT_PLAN: "SUPPLY_ADJUSTMENT_PLAN",
  SUPPLY_ASSIGNMENT_DECISION: "SUPPLY_ASSIGNMENT_DECISION",
};

export const ArrivalBehavior = {
  AUTO_BY_SERVICE_AREA: "AUTO_BY_SERVICE_AREA",
  TEMP_STOP_AND_STANDBY: "TEMP_STOP_AND_STANDBY",
  PARK_AND_STANDBY: "PARK_AND_STANDBY",
};

export const BlockedHandlingPolicy = {
  SAME_SERVICE_AREA_RETRY: "SAME_SERVICE_AREA_RETRY",
  FAIL_FAST: "FAIL_FAST",
  WAIT_DECISION: "WAIT_DECISION",
};

export const ArrivalExecutionResult = {
  NORMAL_ARRIVAL: "NORMAL_ARRIVAL",
  ARRIVED_WITH_TARGET_OCCUPIED: "ARRIVED_WITH_TARGET_OCCUPIED",
  ARRIVED_WITH_TARGET_BLOCKED: "ARRIVED_WITH_TARGET_BLOCKED",
  ARRIVED_WITH_NO_AVAILABLE_STOPPING_CELL: "ARRIVED_WITH_NO_AVAILABLE_STOPPING_CELL",
  ARRIVED_WITH_NO_AVAILABLE_PARKING_CELL: "ARRIVED_WITH_NO_AVAILABLE_PARKING_CELL",
  TARGET_SERVICE_AREA_UNAVAILABLE: "TARGET_SERVICE_AREA_UNAVAILABLE",
  UNKNOWN: "UNKNOWN",
};

export const RoutePlanningStrategy = {
  INITIAL_DEPLOYMENT: "RPS-001",
  ABNORMAL_SAME_SERVICE_AREA: "RPS-002",
};

export const RoutePlanningResult = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};

export const RoutePlanningFailureReason = {
  NONE: "NONE",
  ORIGIN_CELL_INVALID: "ORIGIN_CELL_INVALID",
  TARGET_CELL_INVALID: "TARGET_CELL_INVALID",
  TARGET_SERVICE_AREA_UNAVAILABLE: "TARGET_SERVICE_AREA_UNAVAILABLE",
  NO_AVAILABLE_TARGET_CELL: "NO_AVAILABLE_TARGET_CELL",
  NO_CONNECTED_ROAD_SEGMENT: "NO_CONNECTED_ROAD_SEGMENT",
  ROAD_SEGMENT_BLOCKED: "ROAD_SEGMENT_BLOCKED",
  ROAD_NODE_CONNECTION_INVALID: "ROAD_NODE_CONNECTION_INVALID",
  ROUTE_STEPS_EMPTY: "ROUTE_STEPS_EMPTY",
  ROUTE_STRATEGY_MISMATCH: "ROUTE_STRATEGY_MISMATCH",
  UNKNOWN: "UNKNOWN",
};

export const RouteChangeReason = {
  INITIAL_PLANNING: "INITIAL_PLANNING",
  ABNORMAL_ARRIVAL_REPLAN: "ABNORMAL_ARRIVAL_REPLAN",
};

export const DeploymentFailureReason = {
  NONE: "NONE",
  ROUTE_UNAVAILABLE: "ROUTE_UNAVAILABLE",
  TARGET_UNAVAILABLE: "TARGET_UNAVAILABLE",
  ROBOTAXI_UNAVAILABLE: "ROBOTAXI_UNAVAILABLE",
  UNKNOWN: "UNKNOWN",
};

export const CheckResult = {
  PASSED: "PASSED",
  FAILED: "FAILED",
};

export const IssueType = {
  NONE: "NONE",
  LOW_BATTERY: "LOW_BATTERY",
  CLEANING_REQUIRED: "CLEANING_REQUIRED",
  HARDWARE_FAULT: "HARDWARE_FAULT",
  SENSOR_FAULT: "SENSOR_FAULT",
  SOFTWARE_ISSUE: "SOFTWARE_ISSUE",
  UNKNOWN: "UNKNOWN",
};

export const TaskEventType = {
  AUTO_TRIGGER_STARTED: "AUTO_TRIGGER_STARTED",
  MANUAL_TRIGGER_STARTED: "MANUAL_TRIGGER_STARTED",
  NO_CANDIDATE_ROBOTAXI: "NO_CANDIDATE_ROBOTAXI",
  TASK_CREATED: "TASK_CREATED",
  ROBOTAXI_ALREADY_HAS_PENDING_CHECK_TASK: "ROBOTAXI_ALREADY_HAS_PENDING_CHECK_TASK",
  NO_IDLE_WORKER: "NO_IDLE_WORKER",
  WORKER_ASSIGNED: "WORKER_ASSIGNED",
  CHECK_STARTED: "CHECK_STARTED",
  CHECK_SUBMITTED: "CHECK_SUBMITTED",
  ROBOTAXI_MARKED_AVAILABLE: "ROBOTAXI_MARKED_AVAILABLE",
  ROBOTAXI_MARKED_UNAVAILABLE: "ROBOTAXI_MARKED_UNAVAILABLE",
  TASK_FAILED: "TASK_FAILED",
  DEPLOYMENT_TRIGGER_STARTED: "DEPLOYMENT_TRIGGER_STARTED",
  ROUTE_PLANNED: "ROUTE_PLANNED",
  DEPLOYMENT_STARTED: "DEPLOYMENT_STARTED",
  ROUTE_STEP_ADVANCED: "ROUTE_STEP_ADVANCED",
  ROUTE_EXECUTION_ARRIVED: "ROUTE_EXECUTION_ARRIVED",
  ARRIVAL_NORMAL: "ARRIVAL_NORMAL",
  ARRIVAL_ABNORMAL: "ARRIVAL_ABNORMAL",
  TARGET_REPLACED_WITHIN_SERVICE_AREA: "TARGET_REPLACED_WITHIN_SERVICE_AREA",
  DEPLOYMENT_COMPLETED: "DEPLOYMENT_COMPLETED",
  DEPLOYMENT_FAILED: "DEPLOYMENT_FAILED",
};

export const TaskEventResult = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
};

export function createReadinessCheckTask(task) {
  return task;
}

export function createDeploymentTask(task) {
  return task;
}

export function createRouteExecution(routeExecution) {
  return routeExecution;
}

export function createTaskEventLog(event) {
  return event;
}

export function createRoutePlanningRun(routePlanningRun) {
  return routePlanningRun;
}
