export const TripStatus = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  ON_THE_WAY_PICKUP: "ON_THE_WAY_PICKUP",
  ARRIVED_PICKUP: "ARRIVED_PICKUP",
  PASSENGER_ONBOARD: "PASSENGER_ONBOARD",
  ON_THE_WAY_DESTINATION: "ON_THE_WAY_DESTINATION",
  ARRIVED_DESTINATION: "ARRIVED_DESTINATION",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
};

export const TripPhase = {
  PICKUP: "PICKUP",
  DESTINATION: "DESTINATION",
  COMPLETED: "COMPLETED",
};

export function createTrip(trip) {
  return trip;
}
